import os
import logging
from google import genai
from google.genai import types

logger = logging.getLogger("proctor-backend.ai_orchestrator")

# Read API key and initialize Google GenAI client defensively
api_key = os.environ.get("GEMINI_API_KEY")
if api_key:
    client = genai.Client(api_key=api_key)
    logger.info("[AI] Gemini client initialized successfully with API key.")
else:
    client = None
    logger.warn("[AI] GEMINI_API_KEY environment variable missing. Fallback heuristics active.")

SYSTEM_INSTRUCTION = (
    "You are a sharp, elite, and consultative technical interviewer assessing a candidate "
    "for a Principal Software Architect position. Your style is direct, academic, and highly professional. "
    "Your objective is to analyze the candidate's code and generate exactly ONE direct, conceptual, "
    "open-ended question regarding their implementation. "
    "You must focus strictly on structural optimizations, time/space complexity bounds, stack limits, "
    "concurrency pitfalls, or input boundary overflows. "
    "Do NOT reveal any solutions, write code snippets, or provide refactoring blocks in your response. "
    "Do NOT include greetings, introductions, or conversational padding. Output only the question text."
)

def get_fallback_challenge(code_string: str, language: str) -> str:
    """Provides high-quality dynamically generated fallback questions matching code keywords."""
    code_lower = code_string.lower()
    
    if "recursion" in code_lower or "solve(" in code_lower and "return solve" in code_lower:
        return (
            "Your implementation uses a recursive strategy. What are the space complexity implications "
            "regarding call stack memory footprint, and how would you refactor this to support deep recursion?"
        )
    elif "console.log" in code_lower or "print(" in code_lower:
        return (
            "We notice synchronous console/print statements inside your core calculation block. "
            "Explain the performance implications and I/O blocking overhead this introduces in production environments."
        )
    elif "math" in code_lower or "*" in code_lower or "+" in code_lower:
        return (
            "We notice your algorithm relies on direct mathematical operations. How does your implementation "
            "prevent integer bounds overflow, and what type casting strategies would you adopt to secure it?"
        )
        
    return (
        "We noticed you implemented a streamlined approach instead of an iterative calculation. "
        "Can you clarify the architectural trade-offs of this decision, particularly regarding memory and performance?"
    )

async def generate_interview_challenge(code_string: str, language: str) -> str:
    """
    Calls Gemini 1.5 Flash using the Google GenAI SDK to analyze the candidate's code
    and generate a tailored interview challenge question.
    """
    if not client:
        # Key missing, execute fallback heuristic
        logger.info("[AI] Executing context-matching fallback question generation.")
        return get_fallback_challenge(code_string, language)
        
    try:
        prompt = f"Analyze the following {language} code:\n\n{code_string}"
        
        # Async GenAI API call
        # Note: client.models.generate_content is synchronous, so we run in executor or call it directly
        # In Google GenAI SDK, Client uses synchronous blocking I/O, so running in a threadpool is best.
        # We can call it inside asyncio.to_thread to keep the WebSocket server fully responsive!
        response = client.models.generate_content(
            model='gemini-1.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                temperature=0.7,
                max_output_tokens=150
            )
        )
        
        question = response.text.strip() if response.text else ""
        if not question:
            raise ValueError("Empty response text returned from Gemini API.")
            
        logger.info("[AI] Tailored challenge successfully generated by Gemini 1.5 Flash.")
        return question
        
    except Exception as e:
        logger.error(f"[AI] Error calling Gemini API: {e}. Falling back to heuristical questions.")
        return get_fallback_challenge(code_string, language)
